"""Updated Company model

Revision ID: 478eb1794608
Revises: d9af0a14680a
Create Date: 2024-05-18 13:05:22.857677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478eb1794608'
down_revision: Union[str, None] = 'd9af0a14680a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('assistant_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'company', ['assistant_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'assistant_url')
    # ### end Alembic commands ###
